apiVersion: v1
kind: Service
metadata:
  name: {{ include "boinc.fullname" . }}
  labels:
{{ include "boinc.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodeport: {{ .Values.service.nodeport }} 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "boinc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
